#!/usr/bin/env python3
"""The only way to run the DeluluLang toolchain in this workspace: `python dl.py <subcommand> ...`.

Generated by `delulu-measure ai-usability prepare`. Allowed here: "check", "run", "mcp", "lsp"."""
import json, os, shutil, subprocess, sys, time
HERE = os.path.dirname(os.path.abspath(__file__))
ALLOWED = ["check", "run", "mcp", "lsp"]
# The binary's location is this machine's, so it lives beside this file in `dl.local.json`, which a
# committed record leaves out: a record names no one's disk.
with open(os.path.join(HERE, "dl.local.json"), encoding="utf-8") as f:
    DELULU = json.load(f)["delulu"]
def log(entry):
    with open(os.path.join(HERE, "calls.jsonl"), "a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")
args = sys.argv[1:]
sub = args[0] if args else ""
entry = {"t": time.time(), "argv": args, "allowed": sub in ALLOWED}
if sub not in ALLOWED:
    entry["exit"] = 2
    log(entry)
    print(f"dl.py: `{sub}` is not available in this condition (allowed: {', '.join(ALLOWED)})", file=sys.stderr)
    sys.exit(2)
if sub == "check" and os.path.exists(os.path.join(HERE, "solution.delulu")):
    os.makedirs(os.path.join(HERE, "attempts"), exist_ok=True)
    n = len(os.listdir(os.path.join(HERE, "attempts"))) + 1
    shutil.copy(os.path.join(HERE, "solution.delulu"), os.path.join(HERE, "attempts", f"attempt-{n:02}.delulu"))
    entry["attempt"] = n
env = dict(os.environ, DELULU_NO_FIRST_RUN="1")
p = subprocess.run([DELULU] + args, cwd=HERE, env=env)
entry["exit"] = p.returncode
log(entry)
sys.exit(p.returncode)
