//! `delulu completions` — a shell completion script, generated rather than kept.
//!
//! A completion script is a *copy* of the command list, and a copy is a thing that drifts. This
//! repository has already paid for that once: `deploy` and `fleet` were working commands that
//! `--help` never mentioned, and so escaped the first `--json` contract sweep entirely. A
//! hand-maintained completion file would be the same mistake with a longer fuse, because nobody
//! re-reads a completion script — they just quietly stop being offered a command that exists.
//!
//! So the list comes from [`crate::cli::SUBCOMMANDS`], and a test binds that constant to the
//! dispatcher *and* to the help text. Add a subcommand and forget one of the three, and the build
//! fails naming the one you missed.
//!
//! **No descriptions, deliberately.** `zsh` and `fish` can show a line of prose beside each
//! command, and it would be nicer. It would also be thirty-one sentences restating what `usage()`
//! already says, in a file whose whole purpose here is to not restate anything. A completion that
//! is always right beats one that is prettier until someone edits the wrong copy.

/// The shells a script can be produced for.
const SHELLS: [&str; 4] = ["bash", "zsh", "fish", "powershell"];

pub fn cmd_completions(rest: &[String]) -> i32 {
    let mut shell: Option<&str> = None;
    for a in rest {
        match a.as_str() {
            // There is no JSON form of a shell script, and pretending otherwise would mean
            // emitting something no shell can source. Refused plainly rather than ignored.
            "--json" => {
                eprintln!("error: `completions` emits a shell script, so it has no `--json` form");
                eprintln!("note: `delulu completions <shell>` writes the script to stdout");
                return 2;
            }
            other if other.starts_with('-') => {
                eprintln!("error: unknown option `{other}`\n\n{}", help());
                return 2;
            }
            other => {
                if shell.is_some() {
                    eprintln!("error: `completions` takes one shell\n\n{}", help());
                    return 2;
                }
                match SHELLS.iter().find(|s| **s == other) {
                    Some(s) => shell = Some(s),
                    None => {
                        eprintln!("error: unknown shell `{other}` — expected one of: {}", SHELLS.join(", "));
                        return 2;
                    }
                }
            }
        }
    }
    let Some(shell) = shell else {
        eprintln!("error: `completions` needs a shell\n\n{}", help());
        return 2;
    };

    print!("{}", script(shell));
    0
}

/// The completion script for one shell. Every one of them carries the same command list.
fn script(shell: &str) -> String {
    let cmds = crate::cli::SUBCOMMANDS;
    match shell {
        "bash" => bash(cmds),
        "zsh" => zsh(cmds),
        "fish" => fish(cmds),
        _ => powershell(cmds),
    }
}

fn bash(cmds: &[&str]) -> String {
    format!(
        "# delulu completion for bash — generated by `delulu completions bash`.\n\
         #\n\
         #   eval \"$(delulu completions bash)\"                     # this shell\n\
         #   delulu completions bash > /etc/bash_completion.d/delulu # every shell\n\
         _delulu() {{\n    \
             local cur\n    \
             cur=\"${{COMP_WORDS[COMP_CWORD]}}\"\n    \
             if [ \"${{COMP_CWORD}}\" -eq 1 ]; then\n        \
                 COMPREPLY=($(compgen -W \"{list}\" -- \"${{cur}}\"))\n        \
                 return 0\n    \
             fi\n    \
             # Past the subcommand, paths are the useful thing to offer: nearly every delulu\n    \
             # command takes a file or a package directory.\n    \
             COMPREPLY=($(compgen -f -- \"${{cur}}\"))\n    \
             return 0\n\
         }}\n\
         complete -o default -F _delulu delulu\n",
        list = cmds.join(" ")
    )
}

fn zsh(cmds: &[&str]) -> String {
    format!(
        "#compdef delulu\n\
         # delulu completion for zsh — generated by `delulu completions zsh`.\n\
         #\n\
         #   delulu completions zsh > \"${{fpath[1]}}/_delulu\"   # then restart the shell\n\
         _delulu() {{\n    \
             local -a _delulu_cmds\n    \
             _delulu_cmds=({list})\n    \
             if (( CURRENT == 2 )); then\n        \
                 _describe -t commands 'delulu command' _delulu_cmds\n        \
                 return\n    \
             fi\n    \
             _files\n\
         }}\n\
         _delulu \"$@\"\n",
        list = cmds.join(" ")
    )
}

fn fish(cmds: &[&str]) -> String {
    format!(
        "# delulu completion for fish — generated by `delulu completions fish`.\n\
         #\n\
         #   delulu completions fish > ~/.config/fish/completions/delulu.fish\n\
         complete -c delulu -f\n\
         complete -c delulu -n __fish_use_subcommand -a '{list}'\n\
         complete -c delulu -n 'not __fish_use_subcommand' -F\n",
        list = cmds.join(" ")
    )
}

fn powershell(cmds: &[&str]) -> String {
    let quoted: Vec<String> = cmds.iter().map(|c| format!("'{c}'")).collect();
    format!(
        "# delulu completion for PowerShell — generated by `delulu completions powershell`.\n\
         #\n\
         #   delulu completions powershell | Out-String | Invoke-Expression   # this session\n\
         #   delulu completions powershell >> $PROFILE                        # every session\n\
         Register-ArgumentCompleter -Native -CommandName delulu -ScriptBlock {{\n    \
             param($wordToComplete, $commandAst, $cursorPosition)\n    \
             $commands = @({list})\n    \
             # Only the first word is a subcommand; after that, let PowerShell offer paths.\n    \
             if ($commandAst.CommandElements.Count -le 2) {{\n        \
                 $commands | Where-Object {{ $_ -like \"$wordToComplete*\" }} | ForEach-Object {{\n            \
                     [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n        \
                 }}\n    \
             }}\n\
         }}\n",
        list = quoted.join(", ")
    )
}

fn help() -> String {
    format!(
        "delulu completions — a shell completion script on stdout\n\n\
         USAGE:\n  \
           delulu completions <{shells}>\n\n\
         INSTALL:\n  \
           bash        eval \"$(delulu completions bash)\"\n  \
           zsh         delulu completions zsh > \"${{fpath[1]}}/_delulu\"\n  \
           fish        delulu completions fish > ~/.config/fish/completions/delulu.fish\n  \
           powershell  delulu completions powershell >> $PROFILE\n\n\
         The command list in the script is generated from the one the dispatcher uses, so a\n\
         subcommand cannot exist without being completable. There is no `--json` form: the\n\
         output is a shell script.\n\n\
         Exit 0 on success, 2 on a bad invocation.",
        shells = SHELLS.join("|")
    )
}
